services:
  documentation:
    image: docs
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
    - "80:80"

  backend:
    image: bpm
    build:
      context: .
      dockerfile: bpm/Dockerfile
    ports:
      - "5000:5000"
    restart: always
    environment:
    - CLIENT_ID=${CLIENT_ID}
    - CLIENT_SECRET=${CLIENT_SECRET}
